name: lint runner
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run klint with reviewdog
        uses: ScaCap/action-ktlint@1.3
      - name: Build with Gradle
        run: ./gradlew build